requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /{{.Values.name}}
prelude:
- |
   mkdir -p /{{.Values.name}}/etc/sv && \
   mkdir -p /{{.Values.name}}/var/lib/teleport && \
   mkdir -p /{{.Values.name}}/etc/runit/runsvdir

steps:
{{ $links := list "teleport" "udhcpc"}}
{{ $opts:= dict "sv" "teleport" "links" $links }}
{{ template "runit_service" $opts }}
- mkdir -p /{{.Values.name}}/var/log/teleport
- cp -rfv teleport.yaml /{{.Values.name}}/etc
- touch /{{.Values.name}}/var/log/teleport/.keep