requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /{{.Values.name}}
prelude:
- |
   mkdir -p /${PACKAGE_NAME}/etc/sv && \
   mkdir -p /${PACKAGE_NAME}/etc/runit/runsvdir

steps:
{{ $links := list "tailscaled" "udhcpc"}}
{{ $opts:= dict "sv" "tailscaled" "links" $links }}
{{ template "runit_service" $opts }}
- mkdir -p /${PACKAGE_NAME}/var/log/tailscaled
- mkdir -p /${PACKAGE_NAME}/var/lib/tailscale
- touch /${PACKAGE_NAME}/var/log/tailscaled/.keep
