requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /integration
steps:
- mkdir -p /integration/usr/bin/
- mkdir -p /integration/lib/systemd/system
- cp -rfv *.service /integration/lib/systemd/system
- cp -rfv *.timer /integration/lib/systemd/system
- mkdir -p /integration/etc/yip.d/
- cp -rfv yipfiles/*.yaml /integration/etc/yip.d/
- cp -rfv yip-init /integration/usr/bin/
- chmod +x /integration/usr/bin/yip-init