requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /udhcpc
prelude:
- |
   mkdir -p /${PACKAGE_NAME}/etc/sv && \
   mkdir -p /${PACKAGE_NAME}/etc/runit/runsvdir

steps:
- cp -rfv services/* /${PACKAGE_NAME}/etc/sv/
#- cp -rfv runlevels/* /${PACKAGE_NAME}/etc/runit/runsvdir
- mkdir -p /${PACKAGE_NAME}/var/log/udhcpc
- touch /${PACKAGE_NAME}/var/log/udhcpc/.keep