image: "quay.io/mocaccino/micro:latest"
prelude:
- |
   luet install \
   utils/autoconf utils/yq utils/jq utils/curl development/make libs/zlib vcs/git \
   development/automake development/pkg-config development/m4 \
   system/musl-compat
env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- LUET_YES=true
