requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /integration
steps:
- mkdir -p /integration/usr/bin/
- mkdir -p /integration/lib/systemd/system.conf.d/
- mkdir -p /integration/etc/systemd/systemd
- cp -rfv *.service /integration/lib/systemd/system
- cp -rfv *.env /integration/etc/systemd/system.conf.d/
