stages:
  boot:
       -  name: "system setup"
          commands: 
          # We do ship symlinks, see:
          # https://www.kernel.org/doc/Documentation/filesystems/devpts.txt
          - chmod 666 /dev/pts/ptmx
          - chmod 1777 /tmp
          - chmod 1777 /var/tmp/
          # Docker and alikes
          - mkdir /sys/fs/cgroup/systemd
          - mount -t cgroup -o none,rw,nosuid,nodev,noexec,relatime,xattr,name=systemd cgroup /sys/fs/cgroup/systemd
name: "system setup"
