stages:
  boot:
       -  name: "system setup"
          commands: 
          # We do ship symlinks, see:
          # https://www.kernel.org/doc/Documentation/filesystems/devpts.txt
          - chmod 666 /dev/pts/ptmx
name: "system setup"
