stages:
  boot:
       -  name: "system setup"
          commands:
          # We do ship symlinks, see:
          # https://www.kernel.org/doc/Documentation/filesystems/devpts.txt
          - chmod 666 /dev/pts/ptmx
          - chmod 1777 /tmp
          - chmod 1777 /var/tmp/
          # 2024-12-28: Joost Ruis disable cgroups v1
          # Docker and alikes
          # - mkdir /sys/fs/cgroup/systemd
          # - mount -t cgroup -o none,rw,nosuid,nodev,noexec,relatime,xattr,name=systemd cgroup /sys/fs/cgroup/systemd

          # Disable cgroups v1 if present
          - echo "Disabling cgroups v1 if present..."; for subsystem in $(ls /sys/fs/cgroup); do umount /sys/fs/cgroup/$subsystem || true; done

          # Enable cgroups v2
          - if [ ! -d /sys/fs/cgroup ]; then mkdir -p /sys/fs/cgroup; fi; echo "Mounting cgroups v2..."; mount -t cgroup2 none /sys/fs/cgroup
name: "system setup"
