stages:
  boot:
       -  name: "enable flathub if needed"
          commands:
          - |
              if command -v flatpak &>/dev/null; then
                flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
              fi
name: "add flathub"
