requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /integration
steps:
- mkdir -p /integration/etc/mocaccino/profiles/available
- cp -rfv profiles/{{.Values.name}}.yaml /integration/etc/mocaccino/profiles/available