unpack: true
requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

env:
- LUET_NOLOCK=true
prelude:
- luet install vcs/git utils/ca-certificates
- git clone https://github.com/ivandavidov/minimal.git
- cd minimal && git checkout e4ab26d8ee2e9e2e24d47852474d453b19cb0ced
- rm -rfv /boot || true
steps:
- mv minimal/src/minimal_boot/ /boot/
- sed -i 's/Minimal/MocaccinoOS/g' /boot/bios/EFI/BOOT/startup.nsh
- sed -i 's/Minimal/MocaccinoOS/g' /boot/bios/boot/syslinux/syslinux.cfg
- sed -i 's/Minimal/MocaccinoOS/g' /boot/uefi/loader/entries/mll-x86.conf
- sed -i 's/Minimal/MocaccinoOS/g' /boot/uefi/loader/entries/mll-x86_64.conf
# Needed during ISOIMAGE creation
- cp -rfv /boot/bios/* /
- cp -rfv /boot/uefi/loader /
# Drop x86 boot option
- rm -rfv /boot/uefi/loader/entries/mll-x86.conf
- rm -rfv /loader/entries/mll-x86.conf
# Append cdroot to boot options to trigger MocaccinoOS-live startup scripts
- sed -i 's/rootfs.xz/rootfs.xz cdroot rootdelay=7/g' /boot/uefi/loader/entries/mll-x86_64.conf
- sed -i 's/rootfs.xz/rootfs.xz cdroot rootdelay=7/g' /loader/entries/mll-x86_64.conf
- sed -i 's/APPEND/APPEND cdroot rootdelay=7/g' /boot/bios/boot/syslinux/syslinux.cfg
- sed -i 's/APPEND/APPEND cdroot rootdelay=7/g' /boot/syslinux/syslinux.cfg

includes:
- /boot$|/boot/.*
# Needed ISOIMAGE
- /EFI$|/EFI/.*
- /loader$|/loader/.*
