image: "quay.io/mocaccino/extra"

package_dir: /mocaccino-wallpaper

steps:
- mkdir /mocaccino-wallpaper/usr/share/wallpapers/mocaccino-wallpaper -p
- cp background.jpg /mocaccino-wallpaper/usr/share/wallpapers/mocaccino-wallpaper
