image: "quay.io/mocaccino/extra:latest"

package_dir: /mocaccino-skel
prelude:
- |
   mkdir -p /${PACKAGE_NAME}/usr/sbin
steps:
- cp -rfv mocaccino-init-skel.sh /${PACKAGE_NAME}/usr/sbin/mocaccino-init-skel
- chmod +x /${PACKAGE_NAME}/usr/sbin/mocaccino-init-skel
- mkdir -p /${PACKAGE_NAME}/etc/skel.defaults/entities
- cp -rfv entities/* /${PACKAGE_NAME}/etc/skel.defaults/entities
- cp -rfv rootfs/* /${PACKAGE_NAME}/etc/skel.defaults/
- cp -rfv skel /${PACKAGE_NAME}/etc/
- cp -rfv os-release /${PACKAGE_NAME}/etc
- mkdir /${PACKAGE_NAME}/mnt && touch /${PACKAGE_NAME}/mnt/.keep
- mkdir -p /${PACKAGE_NAME}/etc/luet/config.protect.d
- cp -rf luet.yaml /${PACKAGE_NAME}/etc/luet/luet.yaml
- cp -rf 01_etc.yml /${PACKAGE_NAME}/etc/luet/config.protect.d/01_etc.yml