# SPDX-License-Identifier: CC0-1.0
#
# MocaccinoOS additional software selection - Office
---
mode: optionalmultiple
method: legacy

labels:
    step: "Office"
    step[nl]: "Kantoor"

items:
    - id: evolution
      name: "Evolution"
      description: "Email, calendar and contacts manager."
      packages: [ apps/evolution ]
      screenshot: ":/images/no-selection.png"
    - id: freeoffice
      name: "FreeOffice"
      description: "Compatible alternative to Microsoft Office. (Community repository)"
      packages: [ apps/freeoffice ]
      screenshot: ":/images/no-selection.png"
    - id: libreoffice
      name: "LibreOffice"
      description: "Full-featured free and open-source office suite. (Community repository)"
      packages: [ apps/libreoffice ]
      screenshot: ":/images/no-selection.png"
    - id: calligra
      name: "Calligra"
      description: "KDE office suite and graphics tools. (Community repository)"
      packages: [ apps/calligra ]
      screenshot: ":/images/no-selection.png"
