requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /{{.Values.name}}
steps:
- mkdir -p /${PACKAGE_NAME}/usr/bin/
- mkdir -p /${PACKAGE_NAME}/etc/runit/core-services
- cp -rfv 13-yip.sh /${PACKAGE_NAME}/etc/runit/core-services/13-yip.sh
- chmod +x /${PACKAGE_NAME}/etc/runit/core-services/13-yip.sh
- cp -rfv yip-init /${PACKAGE_NAME}/usr/bin/
- chmod +x /${PACKAGE_NAME}/usr/bin/yip-init

- cp -rfv yip-reconcile /${PACKAGE_NAME}/usr/bin/
- chmod +x /${PACKAGE_NAME}/usr/bin/yip-reconcile

{{ $links := list "yip" "udhcpc" }}
{{ $opts:= dict "sv" "yip" "links" $links }}
{{ template "runit_service" $opts }}
- mkdir -p /${PACKAGE_NAME}/var/log/yip


prelude:
- |
   mkdir -p /${PACKAGE_NAME}/etc/sv && \
   mkdir -p /${PACKAGE_NAME}/etc/runit/runsvdir

