requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /integration
steps:
- mkdir -p /integration/usr/bin/
- mkdir -p /integration/etc/runit/core-services
- cp -rfv 13-yip.sh /integration/etc/runit/core-services/13-yip.sh
- chmod +x /integration/etc/runit/core-services/13-yip.sh
- cp -rfv yip-init /integration/usr/bin/
- chmod +x /integration/usr/bin/yip-init

- cp -rfv yip-reconcile /integration/usr/bin/
- chmod +x /integration/usr/bin/yip-reconcile

{{ $links := list "yip" "udhcpc" }}
{{ $opts:= dict "sv" "yip" "links" $links }}
{{ template "runit_service" $opts }}
- mkdir -p /integration/var/log/yip


prelude:
- |
   mkdir -p /integration/etc/sv && \
   mkdir -p /integration/etc/runit/runsvdir

