requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /{{.Values.name}}
prelude:
- |
   mkdir -p /${PACKAGE_NAME}/etc/sv && \
   mkdir -p /${PACKAGE_NAME}/etc/runit/runsvdir

steps:
- cp -rfv services/* /${PACKAGE_NAME}/etc/sv/
- cp -rfv runlevel/* /${PACKAGE_NAME}/etc/runit/runsvdir
- cp -rfv ntp.conf /${PACKAGE_NAME}/etc/ntp.conf
- mkdir -p /${PACKAGE_NAME}/var/log/${PACKAGE_NAME}
- touch /${PACKAGE_NAME}/var/log/${PACKAGE_NAME}/.keep
