requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

package_dir: /{{.Values.name}}
prelude:
- |
   mkdir -p /${PACKAGE_NAME}/etc/sv && \
   mkdir -p /${PACKAGE_NAME}/etc/runit/runsvdir

steps:
{{ $links := list "ntpd" "udhcpc"}}
{{ $opts:= dict "sv" "ntpd" "links" $links }}
{{ template "runit_service" $opts }}
- cp -rfv ntp.conf /${PACKAGE_NAME}/etc/ntp.conf
- mkdir -p /${PACKAGE_NAME}/var/log/${PACKAGE_NAME}
- touch /${PACKAGE_NAME}/var/log/${PACKAGE_NAME}/.keep
