requires:
- category: "development"
  name: "toolchain"
  version: ">=0"
env:
- LUET_YES=true
- LUET_NOLOCK=true
prelude:
- luet install vcs/git utils/ca-certificates
- git clone https://github.com/ivandavidov/minimal.git
- cd minimal && git checkout 9ac67c9b677396e70efbae239e137509f0372e40
steps:
- mkdir -p minimal/src/minimal_rootfs/etc/profile.d
- rm -f minimal/src/minimal_rootfs/etc/motd
- cp -rfv greeting.sh minimal/src/minimal_rootfs/etc/profile.d/greeting.sh
- cp -rfv 01_prepare.sh minimal/src/minimal_rootfs/etc/01_prepare.sh
- cp -rfv 02_overlay.sh minimal/src/minimal_rootfs/etc/02_overlay.sh
- mkdir /mocaccino-init
- cp -rfv minimal/src/minimal_rootfs/etc /mocaccino-init
- cp -rfv init /mocaccino-init
- cp -rfv minimal/src/minimal_rootfs/var /mocaccino-init

package_dir: /mocaccino-init
