#!/bin/sh

echo -e '\e[2m'
echo -e '        ..'
echo -e '      ..  ..'
echo -e '            ..'
echo -e '             ..'
echo -e '            ..'
echo -e '           ..'
echo -e '         ..'
echo -e '##       ..    ####'
echo -e '##.............##  ##'
echo -e '##.............##   ##'
echo -e '##.............## ##'
echo -e '##.............###'
echo -e ' ##...........##'
echo -e '  #############'
echo -e '  #############'
echo -e '#################'
echo -e ''
echo -e '\e[22mWelcome to \e[33mMocaccinoOS'
echo -e '\e[0m'
