image: "quay.io/mocaccino/extra"

package_dir: /mocaccino-icons

steps:
# 1. Create the destination directory structure
- install -d /usr/share/icons/mOS-icons/scalable/apps/

# 2. Copy the assets
- cp files/mOS_logo.png /usr/share/icons/mOS-icons/
- cp files/mOS_outlined_hl.png /usr/share/icons/mOS-icons/
- cp files/mOS_outlined_hl.svg /usr/share/icons/mOS-icons/scalable/apps/distributor-logo.svg
- cp files/mOS_outlined_w.png /usr/share/icons/mOS-icons/
- cp files/mOS_outlined_w.svg /usr/share/icons/mOS-icons/
- cp files/mOS_coffee_bean.png /usr/share/icons/mOS-icons/

# 3. Create the symlink for the distributor logo
- install -d /usr/share/icons/hicolor/scalable/apps/
- ln -sf /usr/share/icons/mOS-icons/scalable/apps/distributor-logo.svg /usr/share/icons/hicolor/scalable/apps/distributor-logo.svg
